server:
  port: 48884
  servlet:
    context-path: /catalog

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:catalog
    username: user
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect